### PR TITLE
Basic modifications to make it compatible with KSP 1.3. No localization

### PR DESCRIPTION
**Pull request by alcidesv**

### CODE REVIEW

**Comment by sarbian** [comment]
Can you redo the PR on the dev branch (just changing the PR branch in github seems to be a bad idea) ? Or I can use the changes I have in my local branch.

**Comment by sarbian** [comment]
Also, without the Tuple changes please. I want to keep using my local version of smooth since I can't update the KSP one.
Thanks :)

**Comment by alcidesv** [comment]
I'm not familiar with the project and the state of the 'dev' branch. Maybe you can take it from here?

**Comment by sarbian** [comment]
Sure. Thanks for the work 👍

**Pull request closed without merging**
