### PR TITLE
Code modernization push: .NET 4.8 / ALGLIB 3.18 / code-quality refactoring

### PR DESCRIPTION
**Pull request by unquietwiki**
Resolves issues raised by #1510

### CODE REVIEW

**Comment by sarbian** [comment]
And merged. Thanks for the changes. I'll forward to future patch.

**Comment by unquietwiki** [comment]
Thanks @sarbian ! I hope you're keeping safe & well.

**Comment by siimav** [comment]
* Not all Windows machines have .net 4.8. So far 4.7.2 has been a safer bet.
* This .editorconfig file you added isn't even remotely similar to the coding conventions MJ's codebase has followed so far.

**Comment by unquietwiki** [comment]
@siimav Yeah, after further review & discussion with others, 4.7.2 might be an acceptable target; just annoys VS Studio when you try to load the solutions. The editorconfig has been trickier; I've made multiple passes over the code in the past two weeks, and the code still doesn't fully match up, depending on the files (ALGLIB is definitely the outlier, which messes with any code formatting pass). A side note; I ended up upgrading my CPU when I first started looking at this stuff; this code is close to 200 files, and was originally generating hundreds-of-thousands of suggestions & warnings.

Something for you & @sarbian to ponder. I've been making use of the [Unity Analyzers](https://devblogs.microsoft.com/visualstudio/making-our-unity-analyzers-open-source/) & [IDisposable Analyzers](https://github.com/DotNetAnalyzers/IDisposableAnalyzers) to identify problematic code. The Unity one is pretty good at ferreting out things like null-handling; the other one is good about collections, except for some ALGLIB calls. The best result I've managed is that stuff works good, except inconsistent results on "circularize orbit". If I can figure out why that happens, I'm presuming a number of reported bugs would go away.

**Comment by lamont-granquist** [comment]
I think this busted Jenkins builds:

https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/

```
Microsoft (R) Visual C# Compiler version 3.6.0-4.20269.4 (c94e3215)
Copyright (C) Microsoft Corporation. All rights reserved.

Properties/AssemblyInfo.cs(10,12,10,27): error CS0579: Duplicate 'AssemblyCompany' attribute
Properties/AssemblyInfo.cs(11,12,11,27): error CS0579: Duplicate 'AssemblyProduct' attribute
Properties/AssemblyInfo.cs(36,12,36,40): error CS0579: Duplicate 'AssemblyInformationalVersion' attribute
Build step 'Execute shell' marked build as failure
Skipped archiving because build is not successful
Triggering a new build of MechJeb2-CKAN-REPO
Finished: FAILURE
```

**Comment by unquietwiki** [comment]
@lamont-granquist I just checked the source; couldn't find the duplicate; unless it's counting the one in "Tests". Check the copy_build scripts against Jenkins; there could also be old artifacts that aren't getting cleared. I saw something like this happen on at least one other thing I was poking around, but I think that had to do with some template builder.

**Comment by unquietwiki** [comment]
Hey @lamont-granquist @siimav and @sarbian ; I wanted to follow up on all the null stuff we were discussing. This came up while looking at Kopernicus, and I threw together some documentation on the issue & suggested fixes. If you have any feedback on it, lemme know & I'll adjust it accordingly. Thanks!

https://unquietwiki.com/en/TechFindings/UnityNulls

**Pull request merged**
