### PR TITLE
Localization error correction

### PR DESCRIPTION
**Pull request by tinygrox**
image

Sorry to find out now

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Screen Shot 2019-11-24 at 3 40 54 PM

looks like you might have a few more to fix...

**Comment by lamont-granquist** [comment]
Screen Shot 2019-11-24 at 3 44 17 PM

I wonder if I'm just doing something wrong.

Oh, is the localization file getting published correctly via the Makefile?

**Comment by lamont-granquist** [comment]
nevermind.

fixed in #1204

**Comment by tinygrox** [comment]
lol

**Pull request merged**
