### PR TITLE
More localized text

### PR DESCRIPTION
**Pull request by tinygrox**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I think you have line editing issues with this PR?

MechJebCore.cs (for example) shows every line as updating but I don't see the diff, so I think you've converted the lined endings.  You shouldn't need to do that because the .gitattributes file should be treating all `*.cs` files as text and checking them out appropriate for the local system and doing line ending conversions on commit.

**Comment by tinygrox** [comment]
Oh, I uploaded the wrong file. Fix it right away

**Comment by tinygrox** [comment]
I uploaded the wrong files again so I had to spend some more time.And now it should all be done.

**Comment by lamont-granquist** [comment]
Okay, gonna squash and merge this though to collapse the commits down

You might still want to look at the Localization/en-us.cfg file since every line updated there, but I don't think that warrants blocking merging.

**Pull request merged**
