### PR TITLE
Localization stuff

### PR DESCRIPTION
**Pull request by tinygrox**
Improved simplified Chinese Translation.
New localizable text content has been added

### CODE REVIEW

**Comment by tinygrox** [comment]
By the way, is there a solution to localize those text in the "MechJebModuleInfoItems.cs"

image
image

**Comment by lamont-granquist** [comment]
Offhand I'd think you'd need to put in localization identifiers like `ValueInfoItem("#TimeToNode", ...)` and then the code that handled that would need to call `Localizer.Format` on that before using the string, but that's just a guess without actually looking at the code.

**Comment by tinygrox** [comment]
> Offhand I'd think you'd need to put in localization identifiers like `ValueInfoItem("#TimeToNode", ...)` and then the code that handled that would need to call `Localizer.Format` on that before using the string, but that's just a guess without actually looking at the code.

Are you saying that... Like this?
image
I've tried it before and it doesn't work.

**Comment by lamont-granquist** [comment]
MechJebModuleCustomInfoWindow.cs (i think) would need a corresponding patch to support that.  Those C# attributes are consumed there.

**Comment by tinygrox** [comment]
> MechJebModuleCustomInfoWindow.cs (i think) would need a corresponding patch to support that. Those C# attributes are consumed there.

Wow, it worked.Thank you for taking the time to answer this.

**Pull request merged**
