### PR TITLE
Fix more Deg/Rad issues in OrbitExtensions

### PR DESCRIPTION
**Pull request by sarbian**
It seems we missed a few and I guess they have been breaking some module for a long time.

Merge to master so I can push a release with those if this looks good.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
fixes #1609?

**Comment by lamont-granquist** [comment]
and related to #1589?

**Comment by sarbian** [comment]
Yes, it most likely fixes #1609. And this complete #1589 by fixing the remaining Deg uses. However I am surprised nothing broke before that PR...

**Comment by sarbian** [comment]
The fix is now in dev and master. I will do a new release, and hopefully I did not break more than I fixed.

**Comment by lamont-granquist** [comment]
I'll take a look at it today, I got woke up yesterday by hammering and construction at 8am.  Need a bit of caffiene first though.

**Pull request merged**
