### PR TITLE
Script Module - Version 0.5

### PR DESCRIPTION
**Pull request by SPD13**
Add programming logic in Actions:
- If/Then/Else
- For (Repeat)
- While
Add a "Parallel" action to be able to run multiple actions at the same time
Add a lot of variables that can be used in the conditions for "If" and "Wait For".
Refactor the "Wait for" action with the new common "condition" system
Refactor the UI:
- Add icons on the buttons. Change the existing ones with UTF-8 special characters (less blurry)
- Move the "Add" action at the end of the list
- Add a new system with 2 dropdown boxes to select an action. This reduced the previous dropdown size as there were too much actions

### CODE REVIEW

**Comment by sarbian** [comment]
Just Amazing 👍 
I ll try to build an official release somewhere in the weekend if you want to get anything more in before.

**Comment by SPD13** [comment]
Thanks, ok. I will try to do some more testing to ensure everything is
working good.



2016-11-29 20:21 GMT+01:00 sarbian <notifications@github.com>:

**Comment by sarbian** [comment]
Err, I did not notice that the build failed. I guess your forgot to push something 
ScriptsModule/MechJebModuleScriptActionInterceptWithHohmann.cs(14,24,14,38): error CS0115: 'MechJebModuleScriptActionInterceptWithHohmann.activateAction(int)': no suitable method found to override

**Comment by SPD13** [comment]
Ah ok, i removed this files from my UI but forget to remove it from the
Disk.
This action is no more used as i replaced it with "Maneuver" action that
can perform all the available maneuvers (including Hohmann Transfer).
I send a new pull request, sorry for the bug.

2016-11-29 23:14 GMT+01:00 sarbian <notifications@github.com>:

**Pull request merged**
