### PR TITLE
Add a simplified and commented `TimeToPlane` algorithm

### PR DESCRIPTION
**Pull request by dzhu**
This change replaces the previous implementation of `TimeToPlane` with a new one that is simpler and more commented.

It also fixes a bug in the handling of `LANDifference`: because `LANDifference` was subtracted as the very last step in the angle computations, a positive value could cause the output of `TimeToPlane` to be negative, leading to an immediate launch even when that was not correct.

(I'm not sure `LANDifference` is being set in the most useful way to begin with; it seems to always be better to leave it at 0 than use the value MJ fills in after a launch. But that's a separate discussion.)

Also, there is now a special case for very low inclinations (<.01 degrees); since there's such a small difference between different launch times, the function now just returns 0. The old implementation always returned a launch point 90 degrees away when the inclination was exactly 0.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
I actually cleaned that one up months ago on a branch I never pulled due to other issues with it.

I just rescued that in PR #1260, can you look at that and see if it works?  Its a little more extensive than what you had, and I just use one of napier's analogies from spherical trig to solve the problem (which is why I kind of prefer that solution since its just using a prebaked spherical trig algorithm and doesn't require any exposition or proof).

**Comment by lamont-granquist** [comment]
replaced by #1260

**Comment by dzhu** [comment]
Oh neat, that's some cool math.

**Comment by lamont-granquist** [comment]
Yep, mathematicians already solved that one, I just needed to teach myself enough spherical trig to figure out which formula was simplest to apply.

**Pull request closed without merging**
