### PR TITLE
Linux Build Tweaks

### PR DESCRIPTION
**Pull request by ozraven**
Updated .gitignore with build/ directory and updated Makefile with latest directory structure additions; now builds via make under Linux (Ubuntu).

### CODE REVIEW

**Comment by sarbian** [comment]
I had a quick look at the solutions for adding target recursively in a makefile and the complexity is just ridiculous...

**Comment by sarbian** [comment]
Can you change the request destination branch to dev ? We don't want master to be in front of dev.

**Comment by ozraven** [comment]
Will do - sorry about that. :)

**Comment by ozraven** [comment]
Done.

**Pull request closed without merging**
