### PR TITLE
add a .gitattributes file

### PR DESCRIPTION
**Pull request by lamont-granquist**
I think this makes the object store contain LF line endings
consistently, and forces git on windows to do CRLF ending
translations to/from the object store for the user.  That
should mean that *nix users always see LF and windows users
always see CRLF.

Previously i had thought this repo should standardize on CRLF
but that seems to be fighting git being more *nix based and
designed to store LF and do CRLF conversion on windows.

http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

Thus this change also backs out some unix2dos line conversions
that I did previously (which were fixed by git magically when
i added the .gitattributes file).

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

### CODE REVIEW

**Comment by sarbian** [comment]
Good idea, and great link :)
I will push that to all my repo once I am back from my vacations

**Comment by lamont-granquist** [comment]
yeah came up in a work discussion today, but seemed highly relevant here...

**Comment by zyayoung** [comment]
Has each file been changed yet ?

```
zya$ git diff 
warning: CRLF will be replaced by LF in MechJeb2/OrbitExtensions.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/PIDController.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/PartExtensions.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Plans.txt.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Properties/AssemblyInfo.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Properties/Resources.Designer.c
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Properties/Resources.resx.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Properties/shader.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/ReentrySimulation.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/SpeechBubble.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/ToolbarWrapper.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/Vector6.cs.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in MechJeb2/VesselState.cs.
The file will have its original line endings in your working directory.
```

**Comment by lamont-granquist** [comment]
does this fix it?

```
git rm --cached -r .
git reset --hard
git status
```

(obviously do not do that with uncommitted work in the directory that you need since its destructive to the working directory)

**Comment by zyayoung** [comment]
still the same 😅

```
zya$ git status
On branch dev
Your branch is up-to-date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   MechJeb2/CelestialBodyExtensions.cs
	modified:   MechJeb2/CompatibilityChecker.cs
	modified:   MechJeb2/ComputerModule.cs
	modified:   MechJeb2/DisplayModule.cs
	modified:   MechJeb2/GLUtils.cs
	modified:   MechJeb2/InstallChecker.cs
	modified:   MechJeb2/LambertSolver.cs
	modified:   MechJeb2/MathExtensions.cs
	modified:   MechJeb2/MechJebAR202.cs
	modified:   MechJeb2/MechJebModuleCustomInfoWindow.cs
	modified:   MechJeb2/MechJebModuleDockingAutopilot.cs
	modified:   MechJeb2/MechJebModuleDockingGuidance.cs
	modified:   MechJeb2/MechJebModuleFlightRecorder.cs
	modified:   MechJeb2/MechJebModuleInfoItems.cs
	modified:   MechJeb2/MechJebModuleLandingGuidance.cs
	modified:   MechJeb2/MechJebModuleLandingPredictions.cs
	modified:   MechJeb2/MechJebModuleManeuverPlanner.cs
	modified:   MechJeb2/MechJebModuleMenu.cs
	modified:   MechJeb2/MechJebModuleRCSBalancerWindow.cs
	modified:   MechJeb2/MechJebModuleRCSController.cs
	modified:   MechJeb2/MechJebModuleRendezvousAutopilot.cs
	modified:   MechJeb2/MechJebModuleRendezvousAutopilotWindow.cs
	modified:   MechJeb2/MechJebModuleRendezvousGuidance.cs
	modified:   MechJeb2/MechJebModuleRoverController.cs
	modified:   MechJeb2/MechJebModuleRoverWindow.cs
	modified:   MechJeb2/MechJebModuleSettings.cs
	modified:   MechJeb2/MechJebModuleSolarPanelController.cs
	modified:   MechJeb2/MechJebModuleSpaceplaneAutopilot.cs
	modified:   MechJeb2/MechJebModuleSpaceplaneGuidance.cs
	modified:   MechJeb2/MechJebModuleStageStats.cs
	modified:   MechJeb2/MechJebModuleTargetController.cs
	modified:   MechJeb2/MechJebModuleThrustController.cs
	modified:   MechJeb2/MechJebModuleThrustWindow.cs
	modified:   MechJeb2/MechJebModuleTranslatron.cs
	modified:   MechJeb2/ModExtensionDemo.cs
	modified:   MechJeb2/OrbitExtensions.cs
	modified:   MechJeb2/PIDController.cs
	modified:   MechJeb2/PartExtensions.cs
	modified:   MechJeb2/Plans.txt
	modified:   MechJeb2/Properties/AssemblyInfo.cs
	modified:   MechJeb2/Properties/Resources.Designer.cs
	modified:   MechJeb2/Properties/Resources.resx
	modified:   MechJeb2/Properties/shader
	modified:   MechJeb2/ReentrySimulation.cs
	modified:   MechJeb2/SpeechBubble.cs
	modified:   MechJeb2/ToolbarWrapper.cs
	modified:   MechJeb2/Vector6.cs
	modified:   MechJeb2/VesselState.cs

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by zyayoung** [comment]
And the problem also exist in GitHub Desktop.
May I commit and create a pull request to change these files?

problem_in_GitHub_Desktop

**Pull request merged**
