### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Raf04**
1- Improvement of PID to provide a limitation of angular velocity. This does the spins  slower, but best controlled. Also it reduces fuel usage by RCS.

2- Fix error in "VesselState".  AttitudeController thinks it can get some torque from not ignited engines

there has been a mistake, I wanted to merge from last Dev...

### CODE REVIEW

**Comment by sarbian** [comment]
Thanks for the patch but wrong target, you choose master instead of dev

**Comment by sarbian** [comment]
And I don't see your patch on your fork. Strange :(
If you have a problem with the marging send me a zip of the patched code and I ll handle it

**Comment by Raf04** [comment]
Your Zip...

https://www.dropbox.com/s/zoa4zah1sw36tyt/AVlimiter.rar?dl=0

**Comment by Raf04** [comment]
I tested version # 505 in ROV. and continues adding torque from not ignited engines.
Any of following options seem to work well:
                if (!e.getFlameoutState)
                if (!e.flameout)
                if (e.isOperational)
                if (e.getIgnitionState)

**Comment by sarbian** [comment]
e.isOperational is the one I used.

**Comment by Raf04** [comment]
Sorry for my English, I mean that any of the options seem do not work well

**Pull request closed without merging**
